name: SD-test
favicon: null
layout_spectrum: 0.011586481239646673
typography_spectrum: 0.8468694929033518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7270475951954722
  lightness: 0.3562175529077649
  saturation: 0.3455569273792207
  rhythmicContrast: 0.34429000434465706
purpose: []
